## B"H


###
http://localhost:8000/api/v1/products?offset=5&limit=10&sort=price&order=asc

###
GET http://localhost:8000/api/v1/products/search/the?limit=10&sort=price&order=asc

###
GET http://localhost:8000/api/v1/products/122

###
POST http://localhost:8000/api/v1/products
Content-Type: application/json

{
  "title": "New Product",
  "description": "This is a new product",
  "price": 100,
  "category": "electronics",
  "stock": 50
}

###
PATCH http://localhost:8000/api/v1/products/1
Content-Type: application/json

{
  "price": 150
}

###
DELETE http://localhost:8000/api/v1/products/1


########################
# Users Controller
########################

###
http://localhost:8000/api/v1/users

###
GET http://localhost:8000/api/v1/users/1

###
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{

}

###
PATCH http://localhost:8000/api/v1/users/1
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe"
}

###
DELETE http://localhost:8000/api/v1/users/1


###
POST http://localhost:8000/api/v1/products/seed